web:
  build: .
  command: bash -c "waitforservices; pserve local.ini"
  ports:
    - "6543:6543"
  links:
    - postgres
    - es
postgres:
  image: postgres
  ports:
    - "5432:5432"
es:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
