#%RAML 0.8
---
title: Example REST API
documentation:
    - title: Home
      content: |
        Welcome to the example API.
baseUri: http://{host}:{port}/{version}
version: v1
mediaType: application/json
protocols: [HTTP, HTTPS]
securitySchemes:
    - x_token_auth:
        description: Authorization header token policy
        type: x-ApiKey
    - x_ticket_auth:
        description: Standard Pyramid Auth Ticket policy
        type: x-Ticket
        settings:
            secret: auth_tkt_secret
            hashalg: sha512
            cookie_name: ramses_auth_tkt
            http_only: true
    - item_owner_acl:
        description: ACL that allows everyone to read, authenticated to create and item owners to edit item
        type: x-ACL
        settings:
            collection: |
                allow g:admin all
                allow everyone view,options
                allow authenticated create
            item: |
                allow g:admin all
                allow everyone view,options
                allow {{item_owner}} update
    - user_self_acl:
        description: ACL that allows everyone to read, authenticated to create and owner to edit
        type: x-ACL
        settings:
            collection: |
                allow g:admin all
                allow everyone view,options
            item: |
                allow g:admin all
                allow everyone view,options
                allow {{user_self}} update
securedBy: [x_ticket_auth]
resourceTypes:
    - collection:
        description: Collection of <<resourcePathName>>
        get:
            description: Get all <<resourcePathName>>
        post:
            description: Create new item in <<resourcePathName>> collection
        patch:
            description: Update multiple <<resourcePathName>>
        head:
            description: Determine whether a given resource is available
        options:
            description: Retrieve the available HTTP verbs for a given resource
    - item:
        description: Item from <<resourcePathName>> collection
        get:
            description: Get a particular item from <<resourcePathName>> collection
        patch:
            description: Update a particular item from <<resourcePathName>> collection
        put:
            description: Replace a particular item from <<resourcePathName>> collection
        delete:
            description: Delete a particular item from <<resourcePathName>> collection
        head:
            description: Determine whether a given resource is available
        options:
            description: Retrieve the available HTTP verbs for a given resource

/users:
    securedBy: [user_self_acl]
    displayName: All users
    type: collection
    post:
        description: Create a new user
        body:
            application/json:
                schema: !include schemas/user.json

    /{username}:
        type: item
        displayName: One user

        /settings:
            displayName: User settings
            get:
                description: Get all settings of a particular user
            post:
                description: Change a user's settings

        /groups:
            displayName: User groups
            get:
                description: Get all groups of a particular user
            post:
                description: Change a user's groups

        /profile:
            displayName: User profile
            get:
                description: Get a user's profile
            post:
                description: Create a user's profile
                body:
                    application/json:
                        schema: !include schemas/profile.json
            patch:
                description: Update a user's profile

/stories:
    securedBy: [item_owner_acl]
    displayName: All stories
    type: collection
    post:
        description: Create new story
        body:
            application/json:
                schema: !include schemas/story.json
    delete:
        description: Delete multiple stories

    /{id}:
        type: item
        displayName: One story
